import localFont from "next/font/local";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>File Transefer</title>
      </head>
      <body>
        <header>
          {/* <h1>UPSC Preparation Platform</h1> */}
        </header>
        <main>
          {children}
          </main>
        <footer>
          {/* <p>&copy; {new Date().getFullYear()} UPSC Prep</p> */}
        </footer>
      </body>
    </html>
  );

}
